params_listner:
  provider_url: wss://polygon-mumbai.g.alchemy.com/v2/m1ervz2Dh8jIqYNOqMU39EiaD_n_Q7uo
  group_address: 0x104B8c0E5AA2514e8D13C8f94A2D82Fe25664523
db:
  db_url: root:aaa@tcp(127.0.0.1:3306)/SOCDB
server:
  type: port
  bind_ip: 127.0.0.1
  port: 3000
