params_listner:
  provider_url: wss://polygon-mumbai.g.alchemy.com/v2/m1ervz2Dh8jIqYNOqMU39EiaD_n_Q7uo
  group_address: 0x69ff2e622861947876eD40BCaE4eC7c4396C59F3
db:
  db_url: root:aaa@tcp(127.0.0.1:3306)/SOCDB
